fucodo:
  mermaid:

    # is written in the puppeteer config file to guide mermaid to the correct location of the browser
    puppeteer-config:
      executablePath: '/usr/bin/chromium'
      args: ['--no-sandbox']
    svgo-config:
      multipass: true,
      plugins:
        - removeXMLProcInst
        # 1) Regeln aus <style> in style="" Attribute kopieren
        - name: 'inlineStyles'
          params: { onlyMatchedOnce: false, removeMatchedSelectors: true }
        # 2) style="" in einzelne Attribute wie fill/stroke/font-size aufspalten
        - 'convertStyleToAttrs'
        # 3) Aufr√§umen ohne semantisch Relevantes zu verlieren
        - 'cleanupAttrs'
        - 'removeUselessDefs'
        # 4) <style> Block komplett entfernen (nachdem alles geinlined wurde)
        - 'removeStyleElement'
